### PR TITLE
Disable zoom tools in logscale mode

### PR DESCRIPTION
**Pull request by passcod**
Further fixes for #15

### CODE REVIEW

**Comment by passcod** [comment]
I've also added a minor change so the active chart type icon is highlighted

**Comment by seladb** [comment]
Now the new icons are gone...

image

**Comment by passcod** [comment]
Definitely working here :confused: 
image

**Comment by seladb** [comment]
Sorry, my bad, I didn't checkout to the correct branch. It looks good, I'll merge the PR now

**Pull request merged**
